###
POST https://portafolio-1g6k.onrender.com/api/lan 
Content-Type: application/json

{
    "name":"Linux",
    "image":"not found",
    "category":"operating systems"
}
###
GET https://portafolio-1g6k.onrender.com/api/lan/operating systems
Content-Type: application/json